name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    strategy:
      matrix:
        php_version: ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
      - name: Install Deps
        run: composer install
      - name: Test
        run: composer test
